/**
 * Write the OpenAPI 3.1 document and its reference page into the docs site
 * (segmentation spec §6A.2: "Generate OpenAPI 3.1 … and publish an API reference
 * in the existing /docs site").
 *
 *   npm run build:openapi
 *
 * Outputs:
 *   docs-site/public/openapi.json                              (served at /docs/openapi.json)
 *   docs-site/src/content/docs/modules/api-reference.md        (rendered reference)
 *   docs-site/public/reference-card.svg                        (printable white-balance card, spec §5)
 *
 * Generated from the same Zod contracts the server validates with, so the
 * reference cannot drift from what the API accepts.
 */
import { mkdirSync, writeFileSync } from 'node:fs';

// tsx loads api/ as CommonJS; take the namespace's default when present.
const mod = (await import('../api/_openapi.ts')) as { buildOpenApi?: () => Record<string, unknown>; default?: { buildOpenApi: () => Record<string, unknown> } };
const buildOpenApi = mod.buildOpenApi ?? mod.default!.buildOpenApi;

type Schema = {
  type?: string | string[];
  properties?: Record<string, Schema>;
  required?: string[];
  description?: string;
  enum?: unknown[];
  anyOf?: Schema[];
  items?: Schema;
  minimum?: number;
  maximum?: number;
  maxItems?: number;
};

const doc = buildOpenApi() as {
  info: { description: string; version: string };
  paths: Record<string, Record<string, { summary?: string; description?: string; 'x-scope'?: string; 'x-requires-approval'?: boolean; requestBody?: { content: { 'application/json': { schema: Schema } } } }>>;
};

function typeOf(s: Schema): string {
  if (s.enum) return s.enum.map((v) => `\`${JSON.stringify(v)}\``).join(' \\| ');
  if (s.anyOf) return s.anyOf.map(typeOf).join(' \\| ');
  if (s.type === 'array') return `${s.items ? typeOf(s.items) : 'any'}[]${s.maxItems ? ` (≤ ${s.maxItems})` : ''}`;
  const t = Array.isArray(s.type) ? s.type.join(' \\| ') : (s.type ?? 'object');
  const range = s.minimum !== undefined || s.maximum !== undefined ? ` ${s.minimum ?? ''}–${s.maximum ?? ''}` : '';
  return `${t}${range}`;
}

const lines: string[] = [
  '---',
  'title: Module API reference',
  'description: Every /api/v1/assessments endpoint, generated from the Zod contracts the server validates with.',
  '---',
  '',
  ':::danger[Sandbox — investigational, not for clinical use]',
  'Synthetic or public images only. Every response carries `regulatory_status: "investigational"`. Production keys are refused until ARTG inclusion.',
  ':::',
  '',
  '<!-- Generated by `npm run build:openapi` from api/_contracts.ts. Do not edit by hand. -->',
  '',
  doc.info.description,
  '',
  '- **Auth:** `x-api-key: mw_sandbox_…` (or `Authorization: Bearer`). Keys are per organisation, hashed at rest, scoped per module. Mint with `npm run api:key`.',
  '- **Clinician review is enforced:** `/measure`, `/tissue`, `/vlm-features` and `/run` need an `approval_id` from `/approve`, bound to the SHA-256 of the image and of the final mask. A different image or mask is a `403 approval_mismatch`.',
  '- **Every response** carries `request_id`, `api_version`, `engine_version`, `model_versions`, `regulatory_status`; degraded steps add `degraded: true` and `reason`.',
  '- **Errors:** `{ "error": { "code", "message", "request_id" } }`. Codes: `unauthorized`, `forbidden_scope`, `production_unavailable`, `rate_limited` (with `Retry-After`), `invalid_json`, `validation_error`, `approval_required`, `approval_invalid`, `approval_mismatch`, `idempotency_conflict`, `unprocessable`, `internal_error`.',
  '- **Idempotency:** send `Idempotency-Key` on a POST to get the original response back for 24 h.',
  '- **Masks** returned to sandbox keys carry a PNG `tEXt` watermark (`Comment: MendWise sandbox …`). Pixels are untouched.',
  '- Machine-readable: [`/docs/openapi.json`](/docs/openapi.json) or `GET /api/v1/openapi`.',
  '',
];

for (const [path, methods] of Object.entries(doc.paths)) {
  for (const [method, op] of Object.entries(methods)) {
    lines.push(`## \`${method.toUpperCase()} ${path}\``, '');
    if (op.description) lines.push(op.description, '');
    if (op['x-scope']) lines.push(`Scope: \`${op['x-scope']}\`${op['x-requires-approval'] ? ' · **requires `approval_id`**' : ''}`, '');
    const schema = op.requestBody?.content['application/json'].schema;
    if (schema?.properties) {
      lines.push('| Field | Type | Required | Notes |', '|---|---|---|---|');
      for (const [name, prop] of Object.entries(schema.properties)) {
        const required = schema.required?.includes(name) ? 'yes' : '';
        lines.push(`| \`${name}\` | ${typeOf(prop)} | ${required} | ${(prop.description ?? '').replace(/\|/g, '\\|')} |`);
      }
      lines.push('');
    }
  }
}

mkdirSync('docs-site/public', { recursive: true });
writeFileSync('docs-site/public/openapi.json', `${JSON.stringify(doc, null, 2)}\n`);
writeFileSync('docs-site/src/content/docs/modules/api-reference.md', `${lines.join('\n')}\n`);

// A printable reference card: a matte white patch (the white-balance reference,
// spec §5) beside a 2 cm black-bordered square. Print at 100% on matte paper.
writeFileSync(
  'docs-site/public/reference-card.svg',
  `<svg xmlns="http://www.w3.org/2000/svg" width="80mm" height="40mm" viewBox="0 0 80 40">
  <rect x="0" y="0" width="80" height="40" fill="#9CA3AF"/>
  <rect x="4" y="6" width="28" height="28" fill="#FFFFFF"/>
  <rect x="40" y="10" width="20" height="20" fill="none" stroke="#000000" stroke-width="1"/>
  <text x="40" y="36" font-family="Helvetica, Arial, sans-serif" font-size="3" fill="#111827">MendWise reference card · print at 100%</text>
  <text x="4" y="4.5" font-family="Helvetica, Arial, sans-serif" font-size="2.6" fill="#111827">White patch — keep matte, unmarked</text>
</svg>
`,
);
console.log('Wrote docs-site/public/openapi.json, docs-site/public/reference-card.svg and modules/api-reference.md');
